### ISSUE TITLE
Add title prop to ActionBar

### ISSUE THREAD

**Issue by bellacorbo** [vtex-apps/shelf#2]
Now the ActionBar needs to receive the title prop for title display: 

`<ActionBar title={this.props.title} onSave={this.handleSave.bind(this)}/>`

@brenoc

**Comment by brenoc** [comment]
Wait until this get merged:
https://github.com/vtex-apps/storefront-editor/pull/42

**Comment by bellacorbo** [comment]
ok! @brenoc
