### ISSUE TITLE
Storefront settings not working

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/shelf#80]
If I configure "items per page" on Storefront for the shelf (eg.: Related Products on product page), it doesn't render like that on the front-end, and it has weird behaviour. It usually shows 1 or 2 items per page (even if there are more than that shown), instead of the 3/4/5 that can be set per page.

## Expected Behaviour
Slick slider should follow the settings for the app on Storefront.

## Current Behaviour
I think because of `adaptToScreen`, slick doesn't respect the other settings and shows 1 or 2 items, and that behaviour is weird too because on the same screen width it alternates between them.
https://github.com/vtex-apps/shelf/blob/2504a5badf301e495c4614e27e81f47aa5e52ddb/react/ShelfContent.js#L117

## Possible Solution
Remove adaptToScreen and implement responsiveness in another way?

## Steps to Reproduce (for bugs)
On storefront product page, create a configuration for "Related Products" with "Items per page" option o layout tab

## Context
![screenshot at nov 12 10-40-40](https://user-images.githubusercontent.com/27775611/48348585-f1a66000-e668-11e8-9e11-8b49289609fd.png)
![screenshot at nov 12 10-40-59](https://user-images.githubusercontent.com/27775611/48348593-f4a15080-e668-11e8-995e-4fc49a9423b8.png)

## Your Environment
* Version used: latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 70.0.3538.77 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS High Sierra
* Link to your project:

**Comment by brunojdo** [comment]
Thanks. I add this in the backlog. We will be investigating this issue soon. Stay tuned!
